/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchResult.java
 *
 * Created on Apr 9, 2009, 12:10:09 AM
 */

package ui;

import java.io.File;

/**
 * <b>SearchResult</b>
 *
 * <p>This class represents the visual end for a classic presentation of a query based search
 * (i.e. a list item) that will contain various elements such as the name of the document, sample
 * text, and a link to the document.  Instances of <code>SearchResult</code> are what will be passed
 * to <code>SearchPanel</code> as well as <code>VisualPanel</code>.
 */
public class SearchResult extends javax.swing.JPanel
{

    /** Creates new form SearchResult */
    public SearchResult()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set the title for the result.  This is typically the document title.
     * @param title - String that will be used for the title of the result
     */
    public void setTitle(String title)
    {
        
    }

    /**
     * Used as a short description of the result.  This can be sample text containing
     * the index terms.
     * @param text - String of a description of the result
     */
    public void setSampleText(String text)
    {
        
    }

    /**
     * Create a link to the document for opening.
     * @param document - A file object so that the file may be retrieved for user
     * interaction
     */
    public void setLink(File document)
    {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
