/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchResult.java
 *
 * Created on Apr 9, 2009, 12:10:09 AM
 */

package ui;

import documentSearching.Document;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.border.TitledBorder;

/**
 * <b>SearchResult</b>
 *
 * <p>This class represents the visual end for a classic presentation of a query based search item
 * (i.e. a list item) that will contain various elements such as the name of the document, sample
 * text, and a link to the document.  Instances of <code>SearchResult</code> are what will be passed
 * to <code>SearchPanel</code> as well as <code>VisualPanel</code>.
 */
public class SearchResult extends javax.swing.JPanel
{

    /** Creates new form SearchResult */
    public SearchResult()
    {
        initComponents();
    }

    public SearchResult(Document d)
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPane = new javax.swing.JScrollPane();
        documentText = new javax.swing.JTextArea();

        documentText.setBackground(new java.awt.Color(224, 223, 227));
        documentText.setColumns(20);
        documentText.setRows(5);
        textPane.setViewportView(documentText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPane, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(textPane, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set the title for the result.  This is typically the document title.
     * @param title - String that will be used for the title of the result
     */
    public void setTitle(String title)
    {
        TitledBorder tb = BorderFactory.createTitledBorder(title);
        this.setBorder(tb);
    }

    /**
     * Used as a short description of the result.  This can be sample text containing
     * the index terms.
     * @param text - String of a description of the result
     */
    public void setSampleText(String text)
    {
        
    }

    /**
     * Create a link to the document for opening.
     * @param document - A file object so that the file may be retrieved for user
     * interaction
     */
    public void setLink(File document)
    {
        //java.awt.Desktop
        // Use this to launch a file-associated program
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea documentText;
    private javax.swing.JScrollPane textPane;
    // End of variables declaration//GEN-END:variables

}
